version: "3.9"

services:
  n8n:
    build: .
    image: ghcr.io/jamesivyy/n8n-ffmpeg:latest
    container_name: n8n-ffmpeg
    restart: unless-stopped
    ports:
      - "5678:5678"
    volumes:
      - n8n-data:/data
      - n8n-config:/home/node/.n8n

volumes:
  n8n-data:
  n8n-config:
